### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by Loganbacca**
- Added Orion, Vanguard, and 890 Jump
- Fixed the download image link jumping to the top and causing gaps at the top of the downloaded image
- Updated alternate colours

### CODE REVIEW

**Comment by Raylehnhoff** [comment]
Can you add the other color sprites? This tool is used by a lot of people, and only adding the new ships to the black sprite is sure to cause some backlash.

re: the link jumping issue - it was directing to #top to fix that issue previously with some browsers. How extensively did you test this problem?

**Comment by Loganbacca** [comment]
Alternate colour sprites have been updated and added to the PR.

Jumping image fix: I've tested it on Firefox 37, confirmed it's still an issue, and that changing the link fixes it. The chart maker doesn't seem to be working on this PC in Chrome at the moment, so I'm not sure what's going on there. I'll test it in Chrome on another PC later.
I can always remove it from the PR until more testing has been done?

**Comment by Raylehnhoff** [comment]
I'll accept the pull just so we pick up the added assets. Thanks a lot for doing this, it makes me happy that the community is contributing.

If you're interested, can you send me an email with your skype/gtalk/whatever IM client you use and we could talk about the future of this tool? smdaegan@gmail.com

**Comment by Raylehnhoff** [comment]
When I get home from work tonight, I'll merge this up to the gh-pages branch and call it done. Thanks again!

**Pull request merged**
