### PR TITLE
Added Nox

### PR DESCRIPTION
**Pull request by ElArGee**

### CODE REVIEW

**Comment by Raylehnhoff** [comment]
@Loganbacca, I thought we weren't supporting personal vehicles? We don't have the Dragonfly, for example.

**Comment by ElArGee** [comment]
We've had the Dragonfly in for a while. I figured since we already have that, and it is space flight capable I might as well add it in. To me the Ursa and Greycat feel like good examples of things that wouldn't fit on the chart.

**Comment by RommelTJ** [comment]
I know it's none of my business (since I'm not contributing commits) and previously I commented against supporting personal vehicles but I think given the popularity of the Nox my views have changed. I think players will expect it to be available in SCFSD. 

+1 for the suggestion of limiting it to space-flight capable ships, though. That would rule out things like the greycat and also things that are space-flight capable but are not ships, like Jetpacks.

**Comment by Raylehnhoff** [comment]
Yeah - my concern is just that if we support smaller vehicles the tool will get a lot less "Fleet" oriented and more "This is all the crap we own between all of our members", if that makes sense.

I'm not necessarily against adding it, but I do like the suggestion that this tool keeps itself aligned to space-flight capable ships only. The reasons for that are purely arbitrary though, admittedly, and as long as @Loganbacca is fine with the expectation that we support these smaller vehicles I guess we can include it.

Pretty conflicted on the matter -- thanks for your comment @RommelTJ.

**Comment by stefanw1337** [comment]
I mean it's better to add everything, and let the player decide if they want to add it in there as a part of their fleet or leave it in the dark. I mean it shows that the fleet has utility even on ground, that you can put a couple of Rovers in a ship, 

And I suppose they can expand their roasters later down the road to have like only air-on-planet helicopters and such, what will you do then? Still keep dropping them?

**Comment by Raylehnhoff** [comment]
The scope of the project is for Factions to show the ships that they contain.

This gets complicated when you have to define "ship". To the personal user or smaller faction, it would make sense to have this equipment/helicopters/smaller non-space-faring personal vehicles. To larger factions it wouldn't.

My goal for this project is to keep the scope narrow in focus. To me, a ship is space-faring, and that should be the focus of these posters. Keeping the scope down keeps @Loganbacca from having to make new vectors all the time, and keeps the tool from needing constant updates. 

The real harm in adding smaller/lighter craft is that, for cheaper ones, almost every player will have the personal vehicles. This increases scope as more and more options are added for smaller crafts. Imagine a faction with hundreds of members -- realistically nearly every member would have these. Is there a point to showing them? If a craft is effectively mandatory, I don't see a reason to show it off, personally.

To answer your question, if we keep the scope narrow then yes, air-on-planet helicopters would be excluded.

I'm going to give this probably another week for more people to weigh in on. I encourage you to reach out to your faction mates and have them weigh in on this. I'm probably going to go with whatever decision @Loganbacca makes with respect to this, because he's the one that adds these vectors, and at the end of the day it's him that has to do the extra work for the added scope.

**Comment by stefanw1337** [comment]
My fear is that if you don't do this, some other site will. And people move over there and use that instead. And since they offer both, why not stick with that. And that means all the work gone into this will be kinda in vain. I mean some will still sit with you, but there's my concerns, straight out.

**Comment by Raylehnhoff** [comment]
That's not a concern I share. This project is open source, and if someone wanted to fork it and add support for those items they are welcome to do so. Honestly, I wouldn't mind at all if a developer that had more time and passion for a project like this wanted to fork it and build it out further. There's no shortage of enhancements that could be made to this system, I just don't have the time or the willpower to maintain it. Relative to other projects I run, this one is the smallest and non-monetized. That's not to say I don't love it, but it gets the smallest slice of my time pie :)

**Comment by RommelTJ** [comment]
That's a strange concern to have since CIG will probably at some point have org tools of their own and this project makes no money. In short, who cares if someone else decides to add every possible thing in the game?

**Comment by Kosyne** [comment]
I have to agree that restricting this tool to just 'ships' is kind of arbitrary, especially in a game that takes place in more than space. I think that kind of decision would be better left to the users, rather than some kind of 'philosophy' taking that decision away from them. As was said above, detailing out the org's planetside capabilities can be just as useful as detailing their spacefaring roster, especially with a major point of the upcoming 3.0 update being about the NON-space side of things. So, that's just my 2 cents, but I really hope the scope doesn't stay this narrow, especially with 3.0 looming.

**Comment by RommelTJ** [comment]
> I think that kind of decision would be better left to the users, rather than some kind of 'philosophy' taking that decision away from them.

But nobody is doing that. Since this is an open-source project, anyone that wants to can either submit a pull request with new ships or fork the code and create their own tool. This is a practical consideration for the project contributors who only have so much time in a day. CIG has many artists and developers who will create dozens upon dozens of assets. It will become a massive task to support everything. 

@Kosyne Please see here for previous discussion on the topic: https://github.com/Raylehnhoff/SCFSD/issues/40 

Edit: You also have to remember that many ships that CIG has created are not available to backers, but may become acquirable after go-live. You also have to support those ships.

**Comment by stefanw1337** [comment]
> "Since this is an open-source project, anyone that wants to can either submit a pull request with new ships..."

Isn't this already a pull request for Nox?

**Comment by ElArGee** [comment]
In the past year I have added 9 vehicles to the chart.
Each vector takes me maybe 15-30 minutes.
So in the past year I've spent approximately 3.5 hours.

Just for context, this is my ship vector pipeline:

1. ~~Steal~~ ~~liberate~~ acquire ship model from holo viewer on RSI website
2. Import ship model into 3D app
3. Render profile view of ship (only using the alpha channel)
4. Fill in any holes in silhouette in paint app
5. Import into Inkscape
6. Run "Trace Bitmap..." function in Inkscape (Multiple scans: Grays, 8 scans)
7. Pick best vector from scans, delete the rest
8. Scale vector to correct size (using an excel sheet to convert length to pixels)
9. Save vector as SVG
10. Add one line of javascript to project files
11. Commit and PR

Looking at it there are quite a few steps, but there is actually very little manual labor involved. If the 3D models are available in the holo viewer I don't mind converting them as they are added.

I'm honestly not too concerned about the amount of time I invest in this. To me this has always been about filling in a gap until CIG builds the fleet view app.

**Comment by stefanw1337** [comment]
So we're talking 30-45 mins for the Nox(and the Rover) then? And it again comes down to 'philosophy' like the other guy said, and what the community wants. Again, I said like the other guy, add it and let the users/community decide if they want to add those to the chart or not. I mean they could edit the file and add a text saying "x100 000" behind a Nox if they wanted.

I like how this looks and that it organizes the ships based on length? Even though that doesn't always seem to be the case, as it seems the Redeemer is shorter than the Vanguard f.ex. But the Redeemer always ends up under the Vanguard. But maybe that's something that also can be added, a sort based on length or cost?

**Comment by Raylehnhoff** [comment]
I'd like to move further discussion of this topic to #65

**Pull request merged**
